spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Softcube@2019!
    url: jdbc:mysql://192.168.99.100:3306/gestao_financeiraDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true