server:
  port:
    5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 142500
    #url: jdbc:mysql://localhost:3306/expenses_management
    url: jdbc:mysql://bb95d4c42aca2d:3973f103@us-cdbr-iron-east-04.cleardb.net/heroku_7584de5de2b149a?reconnect=false
    username: rafael-moura
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true